# -*- coding: utf-8 -*-
"""Data visualization of Bangladesh Map.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VrGvCGvFhbxiVDV8NU18LY-a940yV-1o
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('places.csv')
df

sns.scatterplot(y = 'latitude', x = 'longitude', data = df)

sns.boxplot(df['latitude'])

sns.boxplot(df['longitude'])

percentile25 = df['latitude'].quantile(0.25)
percentile75 = df['latitude'].quantile(0.75)

percentile25

percentile75

iqr = percentile75 - percentile25
iqr

upper_limit = percentile75 + 1.5 * iqr
lower_limit = percentile25 - 1.5 * iqr

print("Upper limit",upper_limit)
print("Lower limit",lower_limit)

df[df['latitude'] > upper_limit]

df[df['latitude'] < lower_limit]

new_df = df[df['latitude'] < upper_limit]

sns.scatterplot(x = 'longitude', y = 'latitude', data = new_df)

new_df = new_df[new_df['latitude'] > lower_limit]
new_df

sns.scatterplot(x = 'longitude', y = 'latitude', data = new_df)

percentile25 = new_df['longitude'].quantile(0.25)
percentile75 = new_df['longitude'].quantile(0.75)

iqr = percentile75 - percentile25
iqr

upper_limit = percentile75 + 1.5 * iqr
lower_limit = percentile25 - 1.5 * iqr

print("Upper limit",upper_limit)
print("Lower limit",lower_limit)

new_df[new_df['longitude'] > upper_limit]

new_df[new_df['longitude'] < lower_limit]

bd = new_df[new_df['longitude'] >lower_limit]

bd

sns.scatterplot(x = 'longitude', y = 'latitude', data = bd)

plt.figure(figsize=(6, 8))
sns.scatterplot(x = 'longitude', y = 'latitude', data = bd)
plt.show()

bd['longitude'] >=24

bd[(bd['longitude'] < 88.5) & (bd['longitude'] > 88) & (bd['latitude'] > 24) & (bd['latitude'] < 24.3)]

bd[bd['address'] == 'Berhampore, West Bengal, India']

bd = bd[bd['address'] != 'Berhampore, West Bengal, India']
bd

plt.figure(figsize=(6, 8))
sns.scatterplot(x = 'longitude', y = 'latitude', data = bd)
plt.show()

bd[(bd['longitude'] < 88.4) & (bd['longitude'] > 88) & (bd['latitude'] > 25.5) & (bd['latitude'] < 25.8)]

bd = bd[bd['address'] != 'Raiganj, West Bengal, India']
bd

plt.figure(figsize=(6, 8))
sns.scatterplot(x = 'longitude', y = 'latitude', data = bd)
plt.show()

# Display all rows from the DataFrame where 'address' contains 'West Bengal'
west_bengal_rows = bd[bd['address'].str.contains('India', na=False)]

# This will show the filtered DataFrame
west_bengal_rows

# Remove rows where 'address' contains 'West Bengal'
bd = bd[~bd['address'].str.contains('India', na=False)]
bd

plt.figure(figsize=(6, 8))
sns.scatterplot(x = 'longitude', y = 'latitude', data = bd)
plt.show()